//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights1
    {
        public int id { get; set; }
        public string flightCode { get; set; }
        public string departureAirport { get; set; }
        public string arrivalAirport { get; set; }
        public Nullable<System.DateTime> departureDateTime { get; set; }
        public Nullable<System.DateTime> arrivalDateTime { get; set; }
        public string flightStats { get; set; }
        public string reason { get; set; }
        public string seat { get; set; }
        public Nullable<int> price { get; set; }
    }
}
